export const allUserLoginData = [
  {
    userId: "hjugfihszghousrhoguhsropighoi1434",
    name: "Admin",
    email: "admin@gmail.com",
    password: "admin@gmail.com",
    status: "active",
    role:"admin",
  },
  {
    userId: "hjugfihszghousrhoguhsropighoi144",
    name: "Sony",
    email: "rakibulislam667s@gmail.com",
    password: "rakibulislam667s@gmail.com",
    status: "Inactive",
    role:"user",
  },
  {
    userId: "hjugfihszghousrhoguhsropighoi1",
    name: "Rakibul Islam",
    email: "rakibul@gmail.com",
    password: "rakibul@gmail.com",
    status: "Inactive",
    role:"user",
  },
  {
    userId: "hjugfihszghousrhoguhsropighoi12",
    name: "Shamim",
    email: "shamim@gmail.com",
    password: "12345678",
    status: "Inactive",
    role:"user",
  },
  {
    userId: "hjugfihszghousrhoguhsropighoi12",
    name: "Tushar",
    email: "tushar@gmail.com",
    password: "12345678",
    status: "Inactive",
    role:"user",
  },
  {
    userId: "hjugfihszghousrhoguhsropighoi14",
    name: "Habib",
    email: "habibl@gmail.com",
    password: "12345678",
    status: "Inactive",
    role:"user",
  },
  {
    userId: "hjugfihszghousrhoguhsropighoi15",
    name: "abcd",
    email: "abcd@gmail.com",
    password: "12345678",
    status: "Inactive",
    role:"user",
  },
];
